# Generated by Django 4.1 on 2024-02-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('footwearapp', '0002_tbl_customer'),
        ('adminapp', '0008_alter_tbl_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField()),
                ('billno', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footwearapp.tbl_login')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_product')),
            ],
        ),
    ]
