# Generated by Django 4.1 on 2024-02-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0002_tbl_customer'),
        ('adminapp', '0009_alter_tbl_product_price'),
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='tbl_cart',
        ),
    ]
