# Generated by Django 4.1 on 2024-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_book_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deliveryaddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
