# Generated by Django 4.1 on 2024-01-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('subcategoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_category')),
            ],
        ),
    ]
