# Generated by Django 4.1 on 2024-01-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='subcategoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_subcategory'),
        ),
    ]
