# Generated by Django 4.1 on 2024-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_tbl_product_subcategoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='description',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='price',
            field=models.IntegerField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='quantity',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
