# Generated by Django 4.1 on 2024-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_product_description_tbl_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
