# Generated by Django 4.1 on 2024-02-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_alter_tbl_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
