# Generated by Django 4.1 on 2024-02-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_tbl_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='quantity',
            field=models.BigIntegerField(null=True),
        ),
    ]
